//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoUno.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CRUDREntities2 : DbContext
    {
        public CRUDREntities2()
            : base("name=CRUDREntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PERSONAL> PERSONAL { get; set; }
    
        public virtual int AGREGAR(string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<int> eDAD, Nullable<bool> isActive)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var eDADParameter = eDAD.HasValue ?
                new ObjectParameter("EDAD", eDAD) :
                new ObjectParameter("EDAD", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGAR", nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, eDADParameter, isActiveParameter);
        }
    
        public virtual int AGREGAR_DATOS(string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<int> eDAD, Nullable<bool> isActive)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var eDADParameter = eDAD.HasValue ?
                new ObjectParameter("EDAD", eDAD) :
                new ObjectParameter("EDAD", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGAR_DATOS", nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, eDADParameter, isActiveParameter);
        }
    
        public virtual int CARGAR_DATOS(string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<int> eDAD, Nullable<bool> isActive)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var eDADParameter = eDAD.HasValue ?
                new ObjectParameter("EDAD", eDAD) :
                new ObjectParameter("EDAD", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CARGAR_DATOS", nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, eDADParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> LISTAR_ESTADO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("LISTAR_ESTADO");
        }
    
        public virtual ObjectResult<MOSTRAR_DATOS_Result> MOSTRAR_DATOS(Nullable<bool> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MOSTRAR_DATOS_Result>("MOSTRAR_DATOS", isActiveParameter);
        }
    
        public virtual ObjectResult<MOSTRAR_DATOSP_Result> MOSTRAR_DATOSP(Nullable<bool> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MOSTRAR_DATOSP_Result>("MOSTRAR_DATOSP", iDParameter);
        }
    
        public virtual ObjectResult<MOSTRAR_DATOSU_Result> MOSTRAR_DATOSU(Nullable<bool> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MOSTRAR_DATOSU_Result>("MOSTRAR_DATOSU", isActiveParameter);
        }
    
        public virtual ObjectResult<P_SELECCIONAR_Result> P_SELECCIONAR(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_SELECCIONAR_Result>("P_SELECCIONAR", iDParameter);
        }
    
        public virtual ObjectResult<PRO_SELECCIONAR_Result> PRO_SELECCIONAR(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_SELECCIONAR_Result>("PRO_SELECCIONAR", iDParameter);
        }
    
        public virtual ObjectResult<PROC_SELEC_Result> PROC_SELEC(Nullable<int> iD, string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<int> eDAD, Nullable<bool> iosActive, string eLEGIR)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var eDADParameter = eDAD.HasValue ?
                new ObjectParameter("EDAD", eDAD) :
                new ObjectParameter("EDAD", typeof(int));
    
            var iosActiveParameter = iosActive.HasValue ?
                new ObjectParameter("IosActive", iosActive) :
                new ObjectParameter("IosActive", typeof(bool));
    
            var eLEGIRParameter = eLEGIR != null ?
                new ObjectParameter("ELEGIR", eLEGIR) :
                new ObjectParameter("ELEGIR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_SELEC_Result>("PROC_SELEC", iDParameter, nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, eDADParameter, iosActiveParameter, eLEGIRParameter);
        }
    
        public virtual ObjectResult<PROC_TODO_Result> PROC_TODO(Nullable<int> iD, string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<int> eDAD, Nullable<bool> isActive, string eLEGIR)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var eDADParameter = eDAD.HasValue ?
                new ObjectParameter("EDAD", eDAD) :
                new ObjectParameter("EDAD", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var eLEGIRParameter = eLEGIR != null ?
                new ObjectParameter("ELEGIR", eLEGIR) :
                new ObjectParameter("ELEGIR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_TODO_Result>("PROC_TODO", iDParameter, nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, eDADParameter, isActiveParameter, eLEGIRParameter);
        }
    
        public virtual ObjectResult<PROC_TODOP_Result> PROC_TODOP(Nullable<int> iD, string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<int> eDAD, Nullable<bool> isActive, string eLEGIR)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var eDADParameter = eDAD.HasValue ?
                new ObjectParameter("EDAD", eDAD) :
                new ObjectParameter("EDAD", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var eLEGIRParameter = eLEGIR != null ?
                new ObjectParameter("ELEGIR", eLEGIR) :
                new ObjectParameter("ELEGIR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_TODOP_Result>("PROC_TODOP", iDParameter, nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, eDADParameter, isActiveParameter, eLEGIRParameter);
        }
    
        public virtual ObjectResult<PROC_TODOPP_Result> PROC_TODOPP(Nullable<int> iD, string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<int> eDAD, Nullable<bool> isActive, string eLEGIR)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var eDADParameter = eDAD.HasValue ?
                new ObjectParameter("EDAD", eDAD) :
                new ObjectParameter("EDAD", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var eLEGIRParameter = eLEGIR != null ?
                new ObjectParameter("ELEGIR", eLEGIR) :
                new ObjectParameter("ELEGIR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_TODOPP_Result>("PROC_TODOPP", iDParameter, nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, eDADParameter, isActiveParameter, eLEGIRParameter);
        }
    
        public virtual ObjectResult<PROCED_SELEC_Result> PROCED_SELEC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROCED_SELEC_Result>("PROCED_SELEC");
        }
    }
}
